// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/service.proto

package phil0522_znote

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ZNoteRequest struct {
	Command              string   `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Book                 string   `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	NoteId               string   `protobuf:"bytes,3,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZNoteRequest) Reset()         { *m = ZNoteRequest{} }
func (m *ZNoteRequest) String() string { return proto.CompactTextString(m) }
func (*ZNoteRequest) ProtoMessage()    {}
func (*ZNoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{0}
}

func (m *ZNoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZNoteRequest.Unmarshal(m, b)
}
func (m *ZNoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZNoteRequest.Marshal(b, m, deterministic)
}
func (m *ZNoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZNoteRequest.Merge(m, src)
}
func (m *ZNoteRequest) XXX_Size() int {
	return xxx_messageInfo_ZNoteRequest.Size(m)
}
func (m *ZNoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ZNoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ZNoteRequest proto.InternalMessageInfo

func (m *ZNoteRequest) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *ZNoteRequest) GetBook() string {
	if m != nil {
		return m.Book
	}
	return ""
}

func (m *ZNoteRequest) GetNoteId() string {
	if m != nil {
		return m.NoteId
	}
	return ""
}

type ZNoteResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZNoteResponse) Reset()         { *m = ZNoteResponse{} }
func (m *ZNoteResponse) String() string { return proto.CompactTextString(m) }
func (*ZNoteResponse) ProtoMessage()    {}
func (*ZNoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{1}
}

func (m *ZNoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZNoteResponse.Unmarshal(m, b)
}
func (m *ZNoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZNoteResponse.Marshal(b, m, deterministic)
}
func (m *ZNoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZNoteResponse.Merge(m, src)
}
func (m *ZNoteResponse) XXX_Size() int {
	return xxx_messageInfo_ZNoteResponse.Size(m)
}
func (m *ZNoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ZNoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ZNoteResponse proto.InternalMessageInfo

func (m *ZNoteResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type QuitServerRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitServerRequest) Reset()         { *m = QuitServerRequest{} }
func (m *QuitServerRequest) String() string { return proto.CompactTextString(m) }
func (*QuitServerRequest) ProtoMessage()    {}
func (*QuitServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{2}
}

func (m *QuitServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitServerRequest.Unmarshal(m, b)
}
func (m *QuitServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitServerRequest.Marshal(b, m, deterministic)
}
func (m *QuitServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitServerRequest.Merge(m, src)
}
func (m *QuitServerRequest) XXX_Size() int {
	return xxx_messageInfo_QuitServerRequest.Size(m)
}
func (m *QuitServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuitServerRequest proto.InternalMessageInfo

type QuitServerResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitServerResponse) Reset()         { *m = QuitServerResponse{} }
func (m *QuitServerResponse) String() string { return proto.CompactTextString(m) }
func (*QuitServerResponse) ProtoMessage()    {}
func (*QuitServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{3}
}

func (m *QuitServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitServerResponse.Unmarshal(m, b)
}
func (m *QuitServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitServerResponse.Marshal(b, m, deterministic)
}
func (m *QuitServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitServerResponse.Merge(m, src)
}
func (m *QuitServerResponse) XXX_Size() int {
	return xxx_messageInfo_QuitServerResponse.Size(m)
}
func (m *QuitServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuitServerResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ZNoteRequest)(nil), "phil0522.znote.ZNoteRequest")
	proto.RegisterType((*ZNoteResponse)(nil), "phil0522.znote.ZNoteResponse")
	proto.RegisterType((*QuitServerRequest)(nil), "phil0522.znote.QuitServerRequest")
	proto.RegisterType((*QuitServerResponse)(nil), "phil0522.znote.QuitServerResponse")
}

func init() {
	proto.RegisterFile("proto/service.proto", fileDescriptor_c33392ef2c1961ba)
}

var fileDescriptor_c33392ef2c1961ba = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x03, 0xf3, 0x84, 0xf8, 0x0a, 0x32,
	0x32, 0x73, 0x0c, 0x4c, 0x8d, 0x8c, 0xf4, 0xaa, 0xf2, 0xf2, 0x4b, 0x52, 0x95, 0x42, 0xb9, 0x78,
	0xa2, 0xfc, 0xf2, 0x4b, 0x52, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x24, 0xb8, 0xd8,
	0x93, 0xf3, 0x73, 0x73, 0x13, 0xf3, 0x52, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x60, 0x5c,
	0x21, 0x21, 0x2e, 0x96, 0xa4, 0xfc, 0xfc, 0x6c, 0x09, 0x26, 0xb0, 0x30, 0x98, 0x2d, 0x24, 0xce,
	0xc5, 0x0e, 0x32, 0x25, 0x3e, 0x33, 0x45, 0x82, 0x19, 0x2c, 0xcc, 0x06, 0xe2, 0x7a, 0xa6, 0x28,
	0xa9, 0x73, 0xf1, 0x42, 0x8d, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x12, 0xe3, 0x62, 0x2b,
	0x4a, 0x2d, 0x2e, 0xcd, 0x29, 0x81, 0x1a, 0x0b, 0xe5, 0x29, 0x09, 0x73, 0x09, 0x06, 0x96, 0x66,
	0x96, 0x04, 0xa7, 0x16, 0x95, 0xa5, 0x16, 0x41, 0x1d, 0xa1, 0x24, 0xc2, 0x25, 0x84, 0x2c, 0x08,
	0x31, 0xc2, 0x68, 0x1b, 0x23, 0xd4, 0xad, 0xc1, 0x10, 0x1f, 0x09, 0xf9, 0x73, 0xf1, 0xb9, 0x56,
	0xa4, 0x26, 0x97, 0x96, 0xa4, 0x3a, 0x43, 0xdd, 0x28, 0xa3, 0x87, 0xea, 0x3d, 0x3d, 0x64, 0xbf,
	0x49, 0xc9, 0xe2, 0x90, 0x85, 0x98, 0xaf, 0xc4, 0x20, 0x14, 0xca, 0xc5, 0x85, 0xb0, 0x57, 0x48,
	0x11, 0x5d, 0x39, 0x86, 0x43, 0xa5, 0x94, 0xf0, 0x29, 0x81, 0x19, 0x9b, 0xc4, 0x06, 0x0e, 0x7a,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x3e, 0xd1, 0x52, 0x91, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ZNoteServiceClient is the client API for ZNoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ZNoteServiceClient interface {
	ExecuteCommand(ctx context.Context, in *ZNoteRequest, opts ...grpc.CallOption) (*ZNoteResponse, error)
	QuitServer(ctx context.Context, in *QuitServerRequest, opts ...grpc.CallOption) (*QuitServerResponse, error)
}

type zNoteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewZNoteServiceClient(cc grpc.ClientConnInterface) ZNoteServiceClient {
	return &zNoteServiceClient{cc}
}

func (c *zNoteServiceClient) ExecuteCommand(ctx context.Context, in *ZNoteRequest, opts ...grpc.CallOption) (*ZNoteResponse, error) {
	out := new(ZNoteResponse)
	err := c.cc.Invoke(ctx, "/phil0522.znote.ZNoteService/ExecuteCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zNoteServiceClient) QuitServer(ctx context.Context, in *QuitServerRequest, opts ...grpc.CallOption) (*QuitServerResponse, error) {
	out := new(QuitServerResponse)
	err := c.cc.Invoke(ctx, "/phil0522.znote.ZNoteService/QuitServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZNoteServiceServer is the server API for ZNoteService service.
type ZNoteServiceServer interface {
	ExecuteCommand(context.Context, *ZNoteRequest) (*ZNoteResponse, error)
	QuitServer(context.Context, *QuitServerRequest) (*QuitServerResponse, error)
}

// UnimplementedZNoteServiceServer can be embedded to have forward compatible implementations.
type UnimplementedZNoteServiceServer struct {
}

func (*UnimplementedZNoteServiceServer) ExecuteCommand(ctx context.Context, req *ZNoteRequest) (*ZNoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (*UnimplementedZNoteServiceServer) QuitServer(ctx context.Context, req *QuitServerRequest) (*QuitServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuitServer not implemented")
}

func RegisterZNoteServiceServer(s *grpc.Server, srv ZNoteServiceServer) {
	s.RegisterService(&_ZNoteService_serviceDesc, srv)
}

func _ZNoteService_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZNoteServiceServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phil0522.znote.ZNoteService/ExecuteCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZNoteServiceServer).ExecuteCommand(ctx, req.(*ZNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZNoteService_QuitServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuitServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZNoteServiceServer).QuitServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phil0522.znote.ZNoteService/QuitServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZNoteServiceServer).QuitServer(ctx, req.(*QuitServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ZNoteService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "phil0522.znote.ZNoteService",
	HandlerType: (*ZNoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteCommand",
			Handler:    _ZNoteService_ExecuteCommand_Handler,
		},
		{
			MethodName: "QuitServer",
			Handler:    _ZNoteService_QuitServer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
